apiVersion: v1
kind: Service
metadata:
  labels:
    app: argocd-test-nginx
  name: argocd-test-nginx
  namespace: argocd-test
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: argocd-test-nginx
  type: NodePort